import "server-only";
import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import path from "node:path";
import { ulid } from "ulid";

/**
 * Admin-uploaded images live on disk, deliberately *outside* the deployed
 * app directory: `git pull` and `next build` both rewrite that tree on every
 * deploy, so anything stored inside it would be destroyed. In production
 * UPLOAD_DIR points at /home/cartebay/uploads (a sibling of the app checkout,
 * untouched by deploys); locally it falls back to a gitignored folder in the
 * repo so the feature works with no setup.
 */
const UPLOAD_DIR = process.env.UPLOAD_DIR ?? path.join(process.cwd(), ".uploads");

const MAX_BYTES = 3 * 1024 * 1024;

/**
 * The extension is taken from this table, never from the uploaded filename —
 * a filename is attacker-controlled and is the usual way a ".php"/".html"
 * ends up on disk. Keys are the only content types accepted.
 */
const ALLOWED: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
};

/**
 * Content type as *claimed* by the browser is just a form field, so it's
 * checked against the file's actual leading bytes. Without this, an HTML
 * document sent as `image/png` would be stored and later served back from
 * our own origin — same-origin HTML is stored XSS.
 */
function sniff(bytes: Uint8Array): string | null {
  const startsWith = (...sig: number[]) => sig.every((b, i) => bytes[i] === b);
  if (startsWith(0xff, 0xd8, 0xff)) return "image/jpeg";
  if (startsWith(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a)) return "image/png";
  if (startsWith(0x47, 0x49, 0x46, 0x38)) return "image/gif";

  // RIFF....WEBP — the 4-byte length sits between the two markers.
  const ascii = (offset: number, text: string) =>
    [...text].every((ch, i) => bytes[offset + i] === ch.charCodeAt(0));
  if (ascii(0, "RIFF") && ascii(8, "WEBP")) return "image/webp";
  if (ascii(4, "ftyp") && (ascii(8, "avif") || ascii(8, "avis"))) return "image/avif";
  return null;
}

export interface SavedUpload {
  url: string;
  error?: never;
}
export interface UploadError {
  url?: never;
  error: string;
}

/** Subdirectories under UPLOAD_DIR that may be written to or served — an allowlist so a folder name can never widen into an arbitrary path. */
export const UPLOAD_FOLDERS = ["banners", "products", "categories"] as const;
export type UploadFolder = (typeof UPLOAD_FOLDERS)[number];

/** Writes a validated image under UPLOAD_DIR/<folder> and returns the public path app/uploads/[folder]/[file] serves it from. */
export async function saveUploadedImage(file: File, folder: UploadFolder): Promise<SavedUpload | UploadError> {
  if (file.size === 0) return { error: "That file is empty" };
  if (file.size > MAX_BYTES) {
    return { error: `Image must be under ${MAX_BYTES / 1024 / 1024}MB — that one is ${(file.size / 1024 / 1024).toFixed(1)}MB` };
  }

  const bytes = new Uint8Array(await file.arrayBuffer());
  const actualType = sniff(bytes);
  if (!actualType || !ALLOWED[actualType]) {
    return { error: "Unsupported image type — use JPG, PNG, WebP, GIF, or AVIF" };
  }

  const filename = `${ulid()}.${ALLOWED[actualType]}`;
  const dir = path.join(UPLOAD_DIR, folder);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, filename), bytes);

  return { url: `/uploads/${folder}/${filename}` };
}

/** Banner-specific wrapper kept so existing call sites read clearly. */
export function saveBannerImage(file: File): Promise<SavedUpload | UploadError> {
  return saveUploadedImage(file, "banners");
}

export function saveCategoryImage(file: File): Promise<SavedUpload | UploadError> {
  return saveUploadedImage(file, "categories");
}

/**
 * True only for paths this module produced. Callers use it before deleting a
 * replaced image, so a category still pointing at picsum.photos or a CDN
 * doesn't send a stray unlink at a path we never wrote.
 */
export function isManagedUpload(url: string | null | undefined): boolean {
  if (!url) return false;
  const [empty, prefix, folder, filename, ...rest] = url.split("/");
  if (empty !== "" || prefix !== "uploads" || rest.length > 0) return false;
  return (UPLOAD_FOLDERS as readonly string[]).includes(folder) && SAFE_FILENAME.test(filename ?? "");
}

/**
 * Filenames are generated by saveBannerImage as `<ulid>.<ext>`, so anything
 * not matching that shape was not produced here and is rejected before it
 * can reach the filesystem — which is what stops `..%2f..%2fetc%2fpasswd`
 * from ever being joined onto a real path.
 */
const SAFE_FILENAME = /^[0-9A-HJKMNP-TV-Z]{26}\.(jpg|png|webp|gif|avif)$/;

const CONTENT_TYPES: Record<string, string> = {
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
  gif: "image/gif",
  avif: "image/avif",
};

export interface ServedUpload {
  /** A plain ArrayBuffer, not a Uint8Array: only the former is accepted as a Response BodyInit. */
  body: ArrayBuffer;
  contentType: string;
}

export async function readUploadedImage(folder: string, filename: string): Promise<ServedUpload | null> {
  if (!(UPLOAD_FOLDERS as readonly string[]).includes(folder)) return null;
  if (!SAFE_FILENAME.test(filename)) return null;
  const ext = filename.split(".").pop()!;
  try {
    const file = await readFile(path.join(UPLOAD_DIR, folder, filename));
    // Copied into a standalone ArrayBuffer rather than handing back
    // file.buffer, which is a pooled allocation Node shares between reads and
    // would expose unrelated bytes either side of this file's slice.
    const body = new ArrayBuffer(file.byteLength);
    new Uint8Array(body).set(file);
    return { body, contentType: CONTENT_TYPES[ext] };
  } catch {
    return null;
  }
}

/** Best-effort cleanup when an upload is deleted or replaced — a leftover file is harmless, so a failure here never blocks the mutation. */
export async function deleteUploadedImage(url: string): Promise<void> {
  const [, , folder, filename] = url.split("/");
  if (!folder || !filename) return;
  if (!(UPLOAD_FOLDERS as readonly string[]).includes(folder) || !SAFE_FILENAME.test(filename)) return;
  try {
    await unlink(path.join(UPLOAD_DIR, folder, filename));
  } catch {
    // Already gone, or never written — nothing to clean up.
  }
}
