// [name, categorySlugs[]]
export const RAW_BRANDS = [
  ["Apple", ["electronics", "computers-and-tablets", "cell-phones-and-accessories"]],
  ["Samsung", ["electronics", "computers-and-tablets", "cell-phones-and-accessories", "major-appliances"]],
  ["Sony", ["electronics", "video-games-and-consoles", "cameras-and-photography"]],
  ["LG", ["electronics", "major-appliances"]],
  ["Google", ["electronics", "cell-phones-and-accessories"]],
  ["Microsoft", ["computers-and-tablets", "video-games-and-consoles"]],
  ["Dell", ["computers-and-tablets"]],
  ["HP", ["computers-and-tablets", "office-and-school-supplies"]],
  ["Lenovo", ["computers-and-tablets"]],
  ["ASUS", ["computers-and-tablets", "video-games-and-consoles"]],
  ["Acer", ["computers-and-tablets"]],
  ["Bose", ["electronics"]],
  ["JBL", ["electronics"]],
  ["Logitech", ["computers-and-tablets", "video-games-and-consoles"]],
  ["Anker", ["electronics", "cell-phones-and-accessories"]],
  ["Garmin", ["electronics", "sporting-goods-and-outdoors"]],
  ["GoPro", ["cameras-and-photography"]],
  ["Canon", ["cameras-and-photography", "office-and-school-supplies"]],
  ["Nikon", ["cameras-and-photography"]],
  ["Nintendo", ["video-games-and-consoles"]],
  ["PlayStation", ["video-games-and-consoles"]],
  ["Xbox", ["video-games-and-consoles"]],
  ["KitchenAid", ["home-and-kitchen", "major-appliances"]],
  ["Cuisinart", ["home-and-kitchen"]],
  ["Ninja", ["home-and-kitchen"]],
  ["Instant Pot", ["home-and-kitchen"]],
  ["Keurig", ["home-and-kitchen"]],
  ["Dyson", ["home-and-kitchen", "major-appliances"]],
  ["Shark", ["home-and-kitchen", "major-appliances"]],
  ["Whirlpool", ["major-appliances"]],
  ["GE Appliances", ["major-appliances"]],
  ["Bosch", ["major-appliances", "home-improvement-and-tools", "automotive-and-powersports"]],
  ["Breville", ["home-and-kitchen"]],
  ["Le Creuset", ["home-and-kitchen"]],
  ["Ashley Furniture", ["furniture"]],
  ["Nike", ["mens-clothing", "womens-clothing", "shoes", "sporting-goods-and-outdoors"]],
  ["Adidas", ["mens-clothing", "womens-clothing", "shoes", "sporting-goods-and-outdoors"]],
  ["Levi's", ["mens-clothing", "womens-clothing"]],
  ["Under Armour", ["mens-clothing", "womens-clothing", "shoes", "sporting-goods-and-outdoors"]],
  ["Puma", ["shoes", "mens-clothing", "womens-clothing"]],
  ["New Balance", ["shoes", "sporting-goods-and-outdoors"]],
  ["Ralph Lauren", ["mens-clothing", "womens-clothing"]],
  ["Calvin Klein", ["mens-clothing", "womens-clothing"]],
  ["The North Face", ["mens-clothing", "womens-clothing", "sporting-goods-and-outdoors"]],
  ["Columbia", ["mens-clothing", "womens-clothing", "sporting-goods-and-outdoors"]],
  ["Champion", ["mens-clothing", "womens-clothing"]],
  ["Vans", ["shoes"]],
  ["Converse", ["shoes"]],
  ["Skechers", ["shoes"]],
  ["Timberland", ["shoes", "mens-clothing"]],
  ["Pandora", ["jewelry-and-watches"]],
  ["Fossil", ["jewelry-and-watches"]],
  ["Citizen", ["jewelry-and-watches"]],
  ["Seiko", ["jewelry-and-watches"]],
  ["Swarovski", ["jewelry-and-watches"]],
  ["L'Oreal", ["health-and-beauty"]],
  ["Neutrogena", ["health-and-beauty"]],
  ["CeraVe", ["health-and-beauty"]],
  ["Olay", ["health-and-beauty"]],
  ["Dove", ["health-and-beauty"]],
  ["Maybelline", ["health-and-beauty"]],
  ["Wilson", ["sporting-goods-and-outdoors"]],
  ["Coleman", ["sporting-goods-and-outdoors"]],
  ["YETI", ["sporting-goods-and-outdoors", "home-and-kitchen"]],
  ["Callaway", ["sporting-goods-and-outdoors"]],
  ["LEGO", ["toys-games-and-hobbies"]],
  ["Hasbro", ["toys-games-and-hobbies"]],
  ["Mattel", ["toys-games-and-hobbies"]],
  ["Fisher-Price", ["toys-games-and-hobbies", "kids-and-baby"]],
  ["Melissa & Doug", ["toys-games-and-hobbies"]],
  ["Purina", ["pet-supplies"]],
  ["Blue Buffalo", ["pet-supplies"]],
  ["KONG", ["pet-supplies"]],
  ["Yamaha", ["musical-instruments-and-gear"]],
  ["Fender", ["musical-instruments-and-gear"]],
  ["Gibson", ["musical-instruments-and-gear"]],
  ["Roland", ["musical-instruments-and-gear"]],
  ["Michelin", ["automotive-and-powersports"]],
  ["Goodyear", ["automotive-and-powersports"]],
  ["WeatherTech", ["automotive-and-powersports"]],
  ["Sharpie", ["office-and-school-supplies"]],
  ["Post-it", ["office-and-school-supplies"]],
  ["Scotts", ["garden-and-outdoor-living"]],
  ["Weber", ["garden-and-outdoor-living"]],
  ["Black+Decker", ["home-improvement-and-tools", "garden-and-outdoor-living"]],
  ["Craftsman", ["home-improvement-and-tools"]],
  ["DeWalt", ["home-improvement-and-tools"]],
  ["Makita", ["home-improvement-and-tools"]],
  ["Samsonite", ["luggage-and-travel-gear"]],
  ["Travelpro", ["luggage-and-travel-gear"]],
];
